#!/usr/bin/env node
// Generate placeholder PNG icons for Tauri. The real icons will be replaced
// by a designer-reviewed asset before the first release. The PNGs here are
// intentionally deterministic so they can be regenerated byte-for-byte.
//
// Usage: node scripts/generate-icons.mjs
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { deflateSync, crc32 } from "node:zlib";

const __dirname = dirname(fileURLToPath(import.meta.url));
const iconsDir = join(__dirname, "..", "src-tauri", "icons");
mkdirSync(iconsDir, { recursive: true });

/**
 * Encode RGBA bytes into a deterministic PNG buffer.
 * @param {number} width
 * @param {number} height
 * @param {Uint8Array} rgba
 * @returns {Buffer}
 */
function encodePng(width, height, rgba) {
  const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // color type RGBA
  ihdr[10] = 0; // compression
  ihdr[11] = 0; // filter
  ihdr[12] = 0; // interlace

  // Each scanline is prefixed with a filter byte (0 = None).
  const stride = width * 4;
  const filtered = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    filtered[y * (stride + 1)] = 0;
    rgba.subarray(y * stride, y * stride + stride).copy
      ? rgba.subarray(y * stride, y * stride + stride).copy(filtered, y * (stride + 1) + 1)
      : filtered.set(rgba.subarray(y * stride, y * stride + stride), y * (stride + 1) + 1);
  }
  const compressed = deflateSync(filtered);

  const chunk = (type, data) => {
    const len = Buffer.alloc(4);
    len.writeUInt32BE(data.length, 0);
    const typeBuf = Buffer.from(type, "ascii");
    const crcInput = Buffer.concat([typeBuf, data]);
    const crc = Buffer.alloc(4);
    crc.writeUInt32BE(crc32(crcInput) >>> 0, 0);
    return Buffer.concat([len, typeBuf, data, crc]);
  };

  return Buffer.concat([
    signature,
    chunk("IHDR", ihdr),
    chunk("IDAT", compressed),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

/**
 * Render a centred "P" shape on a transparent background.
 * @param {number} size
 * @returns {Uint8Array}
 */
function renderPlaceholder(size) {
  const rgba = new Uint8Array(size * size * 4);
  const cx = size / 2;
  const cy = size / 2;
  const radius = size * 0.4;
  const stroke = Math.max(2, Math.floor(size / 16));
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = (y * size + x) * 4;
      const dx = x - cx;
      const dy = y - cy;
      const r = Math.sqrt(dx * dx + dy * dy);
      const inRing = r > radius - stroke && r < radius;
      const inBar = Math.abs(dx) < stroke && dy < 0 && dy > -radius * 0.9;
      const inGap =
        Math.abs(dx + radius * 0.25) < stroke && dy < -radius * 0.4 && dy > -radius * 0.8;
      const filled = inRing || (inBar && !inGap);
      if (filled) {
        rgba[i] = 0x4f;
        rgba[i + 1] = 0x46;
        rgba[i + 2] = 0xe5;
        rgba[i + 3] = 0xff;
      }
    }
  }
  return rgba;
}

for (const [name, size] of [
  ["32x32.png", 32],
  ["128x128.png", 128],
  ["128x128@2x.png", 256],
  ["icon.png", 512],
  ["tray.png", 32],
]) {
  const buf = renderPlaceholder(size);
  writeFileSync(join(iconsDir, name), encodePng(size, size, buf));
  console.log(`wrote ${name} (${size}x${size})`);
}
