//! Durable cache model and shelf placement primitives.
//!
//! Tracer 07 introduces a per-entry directory layout:
//!
//! ```text
//! <cache_root>/
//!   <capture_id>/
//!     capture.png       // flattened RGBA, atomically renamed into place
//!     bitmap.png        // optional staging bitmap, atomically renamed
//!     metadata.json     // editable metadata, atomically renamed
//!     manifest.json     // the publish sentinel, written last
//! ```
//!
//! The shelf enumerates only entries that have a `manifest.json`. Any
//! directory without a manifest is a partial commit and gets reaped on the
//! next startup scan.
//!
//! The wire shapes here are mirrored in `src/lib/ipc/types.ts`; the
//! round-trip is verified by `src-tauri/tests/ipc_contracts.rs` and
//! `src/lib/ipc/types.test.ts`.

use serde::{Deserialize, Serialize};

use crate::coordinate::{PhysicalBounds, PhysicalSize};
use crate::monitor::MonitorDescriptor;

/// Stable identifier for a committed capture. UUID v4, generated by the
/// Rust core. Mirrors `CaptureResolution::capture_id` for the lifetime of
/// the cache entry.
pub type CaptureId = String;

/// Stable identifier for a shelf card. UUID v4, distinct from
/// `CaptureId`. A card carries one capture, but a single capture could
/// theoretically back multiple pins in the future; the ids are kept
/// independent so the card-id namespace can grow.
pub type ShelfId = String;

/// Editable metadata persisted with every cache entry. Defaults are
/// produced at commit time; the user can update them via the
/// `update_cache_metadata` IPC.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CacheEntryMetadata {
    /// User-visible title. Empty by default.
    pub title: String,
    /// Editable note body. Empty by default.
    pub note: String,
    /// Optional tags. Empty by default.
    #[serde(default)]
    pub tags: Vec<String>,
}

/// A fully-durable cache entry. The shelf renders one of these per card.
/// The struct is the single source of truth for both the on-disk
/// manifest and the IPC payload returned by `request_commit`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CacheEntry {
    /// Capture id (UUID v4) assigned by the Rust core at commit time.
    pub capture_id: CaptureId,
    /// Shelf card id (UUID v4). One entry backs one card.
    pub shelf_id: ShelfId,
    /// Absolute path to the flattened PNG.
    pub png_path: String,
    /// Absolute path to the optional bitmap staging asset, if present.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bitmap_path: Option<String>,
    /// Physical bounds of the flattened PNG.
    pub bounds: PhysicalBounds,
    /// Pixel size of the flattened PNG (== bounds.size; kept for the
    /// frontend's thumbnail sizing path without an extra dereference).
    pub size: PhysicalSize,
    /// Total byte size on disk (PNG + metadata + manifest + bitmap if
    /// present).
    pub size_bytes: u64,
    /// Editable metadata.
    pub metadata: CacheEntryMetadata,
    /// Wall-clock millis when the entry became durable.
    pub created_at_ms: i64,
    /// Wall-clock millis when the entry was last accessed. Refreshed
    /// every time the shelf card is shown or the metadata is edited;
    /// the LRU eviction policy uses it (future tracers).
    pub last_access_at_ms: i64,
    /// Identifier of the monitor whose work area the shelf card is
    /// pinned to. Used so the card repositions correctly when the
    /// primary monitor changes between commits.
    pub monitor_id: String,
}

/// Tracer-10: the file name of the per-entry revision sidecar. The
/// file lives next to `metadata.json` and `manifest.json` and
/// carries the editor scene (annotations, badge counter, tool /
/// style state). Persistence helpers: `Cache::read_revision` and
/// `Cache::write_revision` in `src-tauri/src/cache/store.rs`.
pub const REVISION_JSON_FILE_NAME: &str = "revision.json";

/// Owner label of an active lock on a cache entry. The set of owners is
/// stable for the v1 release: more owners (e.g. a future
/// "AnnotationDraft" lock) can be appended as new enum variants.
///
/// The variants are ordered alphabetically so `BTreeSet<LockOwner>`
/// gives a deterministic lock-ordering across releases — useful for
/// debugging and for the contract tests.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LockOwner {
    /// A shelf card is showing this entry.
    Shelf,
    /// The user has opened the entry in the annotation editor.
    Editor,
    /// The entry is currently being dragged out (OLE IDataObject alive).
    Drag,
    /// The entry is pinned as a reference window.
    Pin,
}

impl LockOwner {
    /// Stable string label for diagnostics and telemetry.
    pub fn label(self) -> &'static str {
        match self {
            Self::Shelf => "shelf",
            Self::Editor => "editor",
            Self::Drag => "drag",
            Self::Pin => "pin",
        }
    }
}

/// Computed shelf placement. The shelf window is one borderless webview
/// positioned at (x, y) inside the work area of one monitor. The card
/// itself is rendered by the webview; this struct only carries the
/// outer-window geometry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ShelfPosition {
    /// Identifier of the monitor whose work area hosts the shelf.
    pub monitor_id: String,
    /// The monitor's work area (physical bounds, already inset from any
    /// taskbar). The shelf sits inside this rectangle.
    pub work_area: PhysicalBounds,
    /// X coordinate of the shelf window's top-left, in physical pixels.
    pub x: i32,
    /// Y coordinate of the shelf window's top-left, in physical pixels.
    pub y: i32,
    /// Width of the shelf window in physical pixels.
    pub width: u32,
    /// Height of the shelf window in physical pixels.
    pub height: u32,
    /// Inset from the work-area edges, in physical pixels. Always 24 in
    /// v1; carried as a field so tests can assert the policy and future
    /// revisions can tweak it without recomputing every call site.
    pub margin_px: u32,
}

impl ShelfPosition {
    /// Default shelf size in v1: 240 wide × 180 tall, 24 px inset from
    /// the bottom-right of the primary monitor's work area.
    pub const DEFAULT_WIDTH: u32 = 240;
    /// Default shelf height in physical pixels.
    pub const DEFAULT_HEIGHT: u32 = 180;
    /// Default inset from the work-area edges, in physical pixels.
    pub const DEFAULT_MARGIN_PX: u32 = 24;

    /// Compute the default placement for the given primary monitor.
    /// The shelf always sits at the bottom-right inside the work area,
    /// 24 px from the right and bottom edges. The left and top edges are
    /// not consulted: the rectangle is anchored to the bottom-right
    /// corner so the card never crosses the taskbar.
    pub fn inside_primary_work_area(monitor: &MonitorDescriptor) -> Self {
        let work_area = monitor.work_area;
        let width = Self::DEFAULT_WIDTH;
        let height = Self::DEFAULT_HEIGHT;
        let margin = i64::from(Self::DEFAULT_MARGIN_PX);
        let right = i64::from(work_area.origin.x) + i64::from(work_area.size.width) - margin;
        let bottom = i64::from(work_area.origin.y) + i64::from(work_area.size.height) - margin;
        let x = (right - i64::from(width)).max(i64::from(work_area.origin.x) + margin) as i32;
        let y = (bottom - i64::from(height)).max(i64::from(work_area.origin.y) + margin) as i32;
        Self {
            monitor_id: monitor.id.clone(),
            work_area,
            x,
            y,
            width,
            height,
            margin_px: Self::DEFAULT_MARGIN_PX,
        }
    }

    /// Width of a single queue card in physical pixels. Used by
    /// [`shelf_queue_position`](Self::shelf_queue_position) to lay out
    /// the multi-card row.
    pub const QUEUE_CARD_WIDTH: u32 = 200;
    /// Height of a single queue card in physical pixels.
    pub const QUEUE_CARD_HEIGHT: u32 = 150;
    /// Gap between adjacent queue cards in physical pixels.
    pub const QUEUE_CARD_GAP: u32 = 12;

    /// Compute the placement of the shelf window for a queue of
    /// `visible_cards` (clamped to `[1, MAX_VISIBLE_CARDS]`). The
    /// window is anchored to the bottom-right of the primary
    /// monitor's work area; its width scales with the visible card
    /// count.
    pub fn shelf_queue_position(monitor: &MonitorDescriptor, visible_cards: usize) -> Self {
        let work_area = monitor.work_area;
        let count = visible_cards.clamp(1, crate::MAX_VISIBLE_CARDS);
        let width = Self::QUEUE_CARD_WIDTH * (count as u32)
            + Self::QUEUE_CARD_GAP * ((count as u32).saturating_sub(1));
        let height = Self::QUEUE_CARD_HEIGHT;
        let margin = i64::from(Self::DEFAULT_MARGIN_PX);
        let right = i64::from(work_area.origin.x) + i64::from(work_area.size.width) - margin;
        let bottom = i64::from(work_area.origin.y) + i64::from(work_area.size.height) - margin;
        let x = (right - i64::from(width)).max(i64::from(work_area.origin.x) + margin) as i32;
        let y = (bottom - i64::from(height)).max(i64::from(work_area.origin.y) + margin) as i32;
        Self {
            monitor_id: monitor.id.clone(),
            work_area,
            x,
            y,
            width,
            height,
            margin_px: Self::DEFAULT_MARGIN_PX,
        }
    }
}

// ---------------------------------------------------------------------------
// Tracer 13: cache policy, statistics, and sweep outcomes.
// ---------------------------------------------------------------------------

/// On-disk schema version for [`CachePolicy`]. Bumped when adding or
/// removing fields. The loader is tolerant of unknown fields, so
/// additive changes don't require a bump; renaming or removing a field
/// does.
pub const CACHE_POLICY_SCHEMA_VERSION: u32 = 1;

/// Maximum total cache size in bytes (250 MiB).
pub const DEFAULT_MAX_BYTES: u64 = 250 * 1024 * 1024;
/// Maximum number of cache entries. 500 matches the spec's default.
pub const DEFAULT_MAX_ENTRIES: u32 = 500;
/// Maximum age of an entry from `last_access_at_ms` in milliseconds
/// (24 hours).
pub const DEFAULT_MAX_AGE_MS: i64 = 24 * 60 * 60 * 1000;
/// Hysteresis low-water ratio. When a sweep exceeds the high-water
/// limits it keeps evicting until current usage drops below this
/// fraction of the limits. 0.8 means "evict until both bytes and
/// entries are at or below 80% of the high-water values".
pub const DEFAULT_LOW_WATER_RATIO: f32 = 0.8;
/// How often the periodic sweeper runs, in milliseconds (15 minutes).
pub const DEFAULT_SWEEP_INTERVAL_MS: i64 = 15 * 60 * 1000;
/// Minimum allowed values for the policy fields. Used by `sanitize`
/// to clamp a tampered settings file.
pub const MIN_MAX_BYTES: u64 = 1024 * 1024; // 1 MiB floor
/// Minimum allowed entry count.
pub const MIN_MAX_ENTRIES: u32 = 1;
/// Minimum allowed entry age in milliseconds.
pub const MIN_MAX_AGE_MS: i64 = 60 * 1000; // 1 minute floor
/// Minimum allowed low-water ratio.
pub const MIN_LOW_WATER_RATIO: f32 = 0.1;
/// Maximum allowed low-water ratio.
pub const MAX_LOW_WATER_RATIO: f32 = 1.0;
/// Minimum allowed sweep interval in milliseconds.
pub const MIN_SWEEP_INTERVAL_MS: i64 = 60 * 1000; // 1 minute floor
/// Maximum allowed sweep interval in milliseconds.
pub const MAX_SWEEP_INTERVAL_MS: i64 = 24 * 60 * 60 * 1000; // 24 h ceiling

/// The user's cache policy. Every field is independently clamped or
/// defaulted by [`CachePolicy::sanitize`] so an invalid settings file
/// never crashes the app.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CachePolicy {
    /// Schema version the on-disk file was written with. The loader
    /// uses this to branch on older files; future migrations live in
    /// `sanitize`.
    pub schema_version: u32,
    /// Upper bound on total cache bytes. The sweeper prunes unlocked
    /// entries until usage drops to the low-water ratio.
    pub max_bytes: u64,
    /// Upper bound on entry count. The sweeper prunes unlocked
    /// entries until count drops to the low-water ratio.
    pub max_entries: u32,
    /// Upper bound on entry age (from `last_access_at_ms`). Expired
    /// entries are pruned regardless of the quota.
    pub max_age_ms: i64,
    /// Hysteresis ratio; the sweep keeps pruning until both byte and
    /// entry usage are at or below this fraction of the high-water
    /// limits. The value is in `(0, 1]`.
    pub low_water_ratio: f32,
    /// Sweep cadence for the periodic background worker. The startup
    /// sweep is independent and runs once on boot.
    pub sweep_interval_ms: i64,
    /// When `true`, the cache is purged on graceful exit. The user
    /// setting is honoured: a panic or kill bypasses the purge.
    pub purge_on_exit: bool,
}

impl Default for CachePolicy {
    fn default() -> Self {
        Self {
            schema_version: CACHE_POLICY_SCHEMA_VERSION,
            max_bytes: DEFAULT_MAX_BYTES,
            max_entries: DEFAULT_MAX_ENTRIES,
            max_age_ms: DEFAULT_MAX_AGE_MS,
            low_water_ratio: DEFAULT_LOW_WATER_RATIO,
            sweep_interval_ms: DEFAULT_SWEEP_INTERVAL_MS,
            purge_on_exit: false,
        }
    }
}

impl CachePolicy {
    /// Clamp every numeric field to its documented range and reset the
    /// schema version. Called by the loader on every read so a
    /// tampered file can never crash the app.
    pub fn sanitize(&self) -> Self {
        Self {
            schema_version: CACHE_POLICY_SCHEMA_VERSION,
            max_bytes: self.max_bytes.clamp(MIN_MAX_BYTES, u64::MAX),
            max_entries: self.max_entries.clamp(MIN_MAX_ENTRIES, u32::MAX),
            max_age_ms: self.max_age_ms.clamp(MIN_MAX_AGE_MS, i64::MAX),
            low_water_ratio: self
                .low_water_ratio
                .clamp(MIN_LOW_WATER_RATIO, MAX_LOW_WATER_RATIO),
            sweep_interval_ms: self
                .sweep_interval_ms
                .clamp(MIN_SWEEP_INTERVAL_MS, MAX_SWEEP_INTERVAL_MS),
            purge_on_exit: self.purge_on_exit,
        }
    }

    /// Low-water byte target. Below this total the sweeper stops
    /// pruning for size.
    pub fn low_water_bytes(&self) -> u64 {
        ((self.max_bytes as f64) * (self.low_water_ratio as f64)) as u64
    }

    /// Low-water entry count target. Below this count the sweeper
    /// stops pruning for count.
    pub fn low_water_entries(&self) -> u32 {
        ((self.max_entries as f64) * (self.low_water_ratio as f64)) as u32
    }
}

/// Live snapshot of the cache's usage. Returned by the
/// `get_cache_stats` IPC and used by the sweeper to decide whether
/// pruning is needed.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CacheStats {
    /// Total bytes used by all currently-durable entries.
    pub total_bytes: u64,
    /// Number of durable entries.
    pub entry_count: u32,
    /// Number of entries locked by something other than the shelf
    /// (e.g. editor / drag / pin owners). The sweeper skips these.
    pub locked_count: u32,
    /// `created_at_ms` of the oldest entry, or `None` when the cache
    /// is empty.
    pub oldest_created_at_ms: Option<i64>,
    /// `last_access_at_ms` of the most-recently-accessed entry, or
    /// `None` when the cache is empty.
    pub newest_access_at_ms: Option<i64>,
}

/// Outcome of a single sweep pass. Returned by the sweeper and
/// surfaced via the `clear_cache` IPC. Partial failures are recorded
/// by *category* (no paths) so the summary stays useful for telemetry
/// without leaking the cache root.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SweepOutcome {
    /// Entries removed because they were expired (TTL) AND unlocked.
    pub expired_evicted: u32,
    /// Entries removed to bring usage below the low-water targets.
    pub quota_evicted: u32,
    /// Total bytes reclaimed from evicted entries (or cleaned debris).
    pub bytes_reclaimed: u64,
    /// Stale `*.tmp` files removed from inside the cache root.
    pub tmp_files_removed: u32,
    /// Zero-byte asset files removed from inside entry directories.
    pub zero_byte_assets_removed: u32,
    /// Empty entry directories removed (no manifest, no files).
    pub unindexed_dirs_removed: u32,
    /// Per-stage failure counts. The list deliberately omits the
    /// failing paths so the response can be surfaced to the UI
    /// without leaking the cache root.
    pub partial_failures: u32,
}

impl SweepOutcome {
    /// Total entries the sweep removed across all eviction paths.
    pub fn total_evicted(&self) -> u32 {
        self.expired_evicted.saturating_add(self.quota_evicted)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::monitor::MonitorDescriptor;

    #[allow(clippy::too_many_arguments)]
    fn monitor(
        id: &str,
        x: i32,
        y: i32,
        w: u32,
        h: u32,
        work_x: i32,
        work_y: i32,
        work_w: u32,
        work_h: u32,
    ) -> MonitorDescriptor {
        let bounds = PhysicalBounds::from_xywh(x, y, w, h);
        let work_area = PhysicalBounds::from_xywh(work_x, work_y, work_w, work_h);
        MonitorDescriptor {
            id: id.to_string(),
            label: format!("Monitor {id}"),
            is_primary: true,
            bounds,
            scale_factor: 1.0,
            work_area,
        }
    }

    #[test]
    fn default_metadata_is_empty() {
        let meta = CacheEntryMetadata::default();
        assert_eq!(meta.title, "");
        assert_eq!(meta.note, "");
        assert!(meta.tags.is_empty());
    }

    #[test]
    fn lock_owner_labels_are_stable() {
        assert_eq!(LockOwner::Shelf.label(), "shelf");
        assert_eq!(LockOwner::Editor.label(), "editor");
        assert_eq!(LockOwner::Drag.label(), "drag");
        assert_eq!(LockOwner::Pin.label(), "pin");
    }

    #[test]
    fn shelf_position_sits_24px_inside_work_area() {
        let monitor = monitor(
            "primary", 0, 0, 1920, 1080, 0, 0, 1920, 1040, // taskbar is 40 px tall
        );
        let pos = ShelfPosition::inside_primary_work_area(&monitor);
        // Right edge of the card must be 24 px left of the work-area's
        // right edge.
        let right = i64::from(pos.x) + i64::from(pos.width);
        let wa_right = i64::from(pos.work_area.origin.x) + i64::from(pos.work_area.size.width);
        assert_eq!(wa_right - right, 24);
        // Bottom edge of the card must be 24 px above the work-area's
        // bottom edge.
        let bottom = i64::from(pos.y) + i64::from(pos.height);
        let wa_bottom = i64::from(pos.work_area.origin.y) + i64::from(pos.work_area.size.height);
        assert_eq!(wa_bottom - bottom, 24);
        // The card must not cross the left or top of the work area.
        assert!(pos.x >= pos.work_area.origin.x + 24);
        assert!(pos.y >= pos.work_area.origin.y + 24);
        // The width and height must be the documented defaults.
        assert_eq!(pos.width, ShelfPosition::DEFAULT_WIDTH);
        assert_eq!(pos.height, ShelfPosition::DEFAULT_HEIGHT);
        assert_eq!(pos.margin_px, 24);
    }

    #[test]
    fn shelf_position_handles_negative_origin_work_area() {
        let monitor = monitor("primary", -1920, 0, 1920, 1080, -1920, 0, 1920, 1040);
        let pos = ShelfPosition::inside_primary_work_area(&monitor);
        // Right edge stays 24 px inside the work-area's right edge even
        // with a negative origin.
        let right = i64::from(pos.x) + i64::from(pos.width);
        let wa_right = i64::from(pos.work_area.origin.x) + i64::from(pos.work_area.size.width);
        assert_eq!(wa_right - right, 24);
        // X must land inside the work area.
        assert!(pos.x >= pos.work_area.origin.x);
    }

    #[test]
    fn cache_policy_defaults_match_spec() {
        // The defaults are pinned by the spec (issue #25). Bumping
        // these without a coordinated front-end change is a breaking
        // change.
        let p = CachePolicy::default();
        assert_eq!(p.schema_version, CACHE_POLICY_SCHEMA_VERSION);
        assert_eq!(p.max_bytes, DEFAULT_MAX_BYTES);
        assert_eq!(p.max_entries, DEFAULT_MAX_ENTRIES);
        assert_eq!(p.max_age_ms, DEFAULT_MAX_AGE_MS);
        assert_eq!(p.low_water_ratio, DEFAULT_LOW_WATER_RATIO);
        assert_eq!(p.sweep_interval_ms, DEFAULT_SWEEP_INTERVAL_MS);
        assert!(!p.purge_on_exit);
    }

    #[test]
    fn cache_policy_sanitize_clamps_out_of_range() {
        let dirty = CachePolicy {
            schema_version: 99,
            max_bytes: 10,
            max_entries: 0,
            max_age_ms: 5,
            low_water_ratio: 7.0,
            sweep_interval_ms: 10,
            purge_on_exit: false,
        };
        let clean = dirty.sanitize();
        assert_eq!(clean.schema_version, CACHE_POLICY_SCHEMA_VERSION);
        assert_eq!(clean.max_bytes, MIN_MAX_BYTES);
        assert_eq!(clean.max_entries, MIN_MAX_ENTRIES);
        assert_eq!(clean.max_age_ms, MIN_MAX_AGE_MS);
        assert_eq!(clean.low_water_ratio, MAX_LOW_WATER_RATIO);
        assert_eq!(clean.sweep_interval_ms, MIN_SWEEP_INTERVAL_MS);
    }

    #[test]
    fn cache_policy_low_water_targets() {
        let p = CachePolicy {
            max_bytes: 1000,
            max_entries: 20,
            low_water_ratio: 0.5,
            ..CachePolicy::default()
        };
        assert_eq!(p.low_water_bytes(), 500);
        assert_eq!(p.low_water_entries(), 10);
    }

    #[test]
    fn cache_policy_unknown_fields_are_tolerated() {
        let json = r#"{
            "schemaVersion": 1,
            "maxBytes": 1024,
            "maxEntries": 2,
            "maxAgeMs": 60000,
            "lowWaterRatio": 0.5,
            "sweepIntervalMs": 60000,
            "purgeOnExit": false,
            "futureField": "ignored"
        }"#;
        let parsed: CachePolicy = serde_json::from_str(json).expect("parse");
        assert_eq!(parsed.max_bytes, 1024);
        assert_eq!(parsed.max_entries, 2);
    }

    #[test]
    fn sweep_outcome_total_evicted_sums_both_kinds() {
        let o = SweepOutcome {
            expired_evicted: 3,
            quota_evicted: 5,
            ..SweepOutcome::default()
        };
        assert_eq!(o.total_evicted(), 8);
    }
}
