//! Durable cache model and shelf placement primitives.
//!
//! Tracer 07 introduces a per-entry directory layout:
//!
//! ```text
//! <cache_root>/
//!   <capture_id>/
//!     capture.png       // flattened RGBA, atomically renamed into place
//!     bitmap.png        // optional staging bitmap, atomically renamed
//!     metadata.json     // editable metadata, atomically renamed
//!     manifest.json     // the publish sentinel, written last
//! ```
//!
//! The shelf enumerates only entries that have a `manifest.json`. Any
//! directory without a manifest is a partial commit and gets reaped on the
//! next startup scan.
//!
//! The wire shapes here are mirrored in `src/lib/ipc/types.ts`; the
//! round-trip is verified by `src-tauri/tests/ipc_contracts.rs` and
//! `src/lib/ipc/types.test.ts`.

use serde::{Deserialize, Serialize};

use crate::coordinate::{PhysicalBounds, PhysicalSize};
use crate::monitor::MonitorDescriptor;

/// Stable identifier for a committed capture. UUID v4, generated by the
/// Rust core. Mirrors `CaptureResolution::capture_id` for the lifetime of
/// the cache entry.
pub type CaptureId = String;

/// Stable identifier for a shelf card. UUID v4, distinct from
/// `CaptureId`. A card carries one capture, but a single capture could
/// theoretically back multiple pins in the future; the ids are kept
/// independent so the card-id namespace can grow.
pub type ShelfId = String;

/// Editable metadata persisted with every cache entry. Defaults are
/// produced at commit time; the user can update them via the
/// `update_cache_metadata` IPC.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CacheEntryMetadata {
    /// User-visible title. Empty by default.
    pub title: String,
    /// Editable note body. Empty by default.
    pub note: String,
    /// Optional tags. Empty by default.
    #[serde(default)]
    pub tags: Vec<String>,
}

/// A fully-durable cache entry. The shelf renders one of these per card.
/// The struct is the single source of truth for both the on-disk
/// manifest and the IPC payload returned by `request_commit`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CacheEntry {
    /// Capture id (UUID v4) assigned by the Rust core at commit time.
    pub capture_id: CaptureId,
    /// Shelf card id (UUID v4). One entry backs one card.
    pub shelf_id: ShelfId,
    /// Absolute path to the flattened PNG.
    pub png_path: String,
    /// Absolute path to the optional bitmap staging asset, if present.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bitmap_path: Option<String>,
    /// Physical bounds of the flattened PNG.
    pub bounds: PhysicalBounds,
    /// Pixel size of the flattened PNG (== bounds.size; kept for the
    /// frontend's thumbnail sizing path without an extra dereference).
    pub size: PhysicalSize,
    /// Total byte size on disk (PNG + metadata + manifest + bitmap if
    /// present).
    pub size_bytes: u64,
    /// Editable metadata.
    pub metadata: CacheEntryMetadata,
    /// Wall-clock millis when the entry became durable.
    pub created_at_ms: i64,
    /// Wall-clock millis when the entry was last accessed. Refreshed
    /// every time the shelf card is shown or the metadata is edited;
    /// the LRU eviction policy uses it (future tracers).
    pub last_access_at_ms: i64,
    /// Identifier of the monitor whose work area the shelf card is
    /// pinned to. Used so the card repositions correctly when the
    /// primary monitor changes between commits.
    pub monitor_id: String,
}

/// Owner label of an active lock on a cache entry. The set of owners is
/// stable for the v1 release: more owners (e.g. a future
/// "AnnotationDraft" lock) can be appended as new enum variants.
///
/// The variants are ordered alphabetically so `BTreeSet<LockOwner>`
/// gives a deterministic lock-ordering across releases — useful for
/// debugging and for the contract tests.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LockOwner {
    /// A shelf card is showing this entry.
    Shelf,
    /// The user has opened the entry in the annotation editor.
    Editor,
    /// The entry is currently being dragged out (OLE IDataObject alive).
    Drag,
    /// The entry is pinned as a reference window.
    Pin,
}

impl LockOwner {
    /// Stable string label for diagnostics and telemetry.
    pub fn label(self) -> &'static str {
        match self {
            Self::Shelf => "shelf",
            Self::Editor => "editor",
            Self::Drag => "drag",
            Self::Pin => "pin",
        }
    }
}

/// Computed shelf placement. The shelf window is one borderless webview
/// positioned at (x, y) inside the work area of one monitor. The card
/// itself is rendered by the webview; this struct only carries the
/// outer-window geometry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ShelfPosition {
    /// Identifier of the monitor whose work area hosts the shelf.
    pub monitor_id: String,
    /// The monitor's work area (physical bounds, already inset from any
    /// taskbar). The shelf sits inside this rectangle.
    pub work_area: PhysicalBounds,
    /// X coordinate of the shelf window's top-left, in physical pixels.
    pub x: i32,
    /// Y coordinate of the shelf window's top-left, in physical pixels.
    pub y: i32,
    /// Width of the shelf window in physical pixels.
    pub width: u32,
    /// Height of the shelf window in physical pixels.
    pub height: u32,
    /// Inset from the work-area edges, in physical pixels. Always 24 in
    /// v1; carried as a field so tests can assert the policy and future
    /// revisions can tweak it without recomputing every call site.
    pub margin_px: u32,
}

impl ShelfPosition {
    /// Default shelf size in v1: 240 wide × 180 tall, 24 px inset from
    /// the bottom-right of the primary monitor's work area.
    pub const DEFAULT_WIDTH: u32 = 240;
    /// Default shelf height in physical pixels.
    pub const DEFAULT_HEIGHT: u32 = 180;
    /// Default inset from the work-area edges, in physical pixels.
    pub const DEFAULT_MARGIN_PX: u32 = 24;

    /// Compute the default placement for the given primary monitor.
    /// The shelf always sits at the bottom-right inside the work area,
    /// 24 px from the right and bottom edges. The left and top edges are
    /// not consulted: the rectangle is anchored to the bottom-right
    /// corner so the card never crosses the taskbar.
    pub fn inside_primary_work_area(monitor: &MonitorDescriptor) -> Self {
        let work_area = monitor.work_area;
        let width = Self::DEFAULT_WIDTH;
        let height = Self::DEFAULT_HEIGHT;
        let margin = i64::from(Self::DEFAULT_MARGIN_PX);
        let right = i64::from(work_area.origin.x) + i64::from(work_area.size.width) - margin;
        let bottom = i64::from(work_area.origin.y) + i64::from(work_area.size.height) - margin;
        let x = (right - i64::from(width)).max(i64::from(work_area.origin.x) + margin) as i32;
        let y = (bottom - i64::from(height)).max(i64::from(work_area.origin.y) + margin) as i32;
        Self {
            monitor_id: monitor.id.clone(),
            work_area,
            x,
            y,
            width,
            height,
            margin_px: Self::DEFAULT_MARGIN_PX,
        }
    }

    /// Width of a single queue card in physical pixels. Used by
    /// [`shelf_queue_position`](Self::shelf_queue_position) to lay out
    /// the multi-card row.
    pub const QUEUE_CARD_WIDTH: u32 = 200;
    /// Height of a single queue card in physical pixels.
    pub const QUEUE_CARD_HEIGHT: u32 = 150;
    /// Gap between adjacent queue cards in physical pixels.
    pub const QUEUE_CARD_GAP: u32 = 12;

    /// Compute the placement of the shelf window for a queue of
    /// `visible_cards` (clamped to `[1, MAX_VISIBLE_CARDS]`). The
    /// window is anchored to the bottom-right of the primary
    /// monitor's work area; its width scales with the visible card
    /// count.
    pub fn shelf_queue_position(monitor: &MonitorDescriptor, visible_cards: usize) -> Self {
        let work_area = monitor.work_area;
        let count = visible_cards.clamp(1, crate::MAX_VISIBLE_CARDS);
        let width = Self::QUEUE_CARD_WIDTH * (count as u32)
            + Self::QUEUE_CARD_GAP * ((count as u32).saturating_sub(1));
        let height = Self::QUEUE_CARD_HEIGHT;
        let margin = i64::from(Self::DEFAULT_MARGIN_PX);
        let right = i64::from(work_area.origin.x) + i64::from(work_area.size.width) - margin;
        let bottom = i64::from(work_area.origin.y) + i64::from(work_area.size.height) - margin;
        let x = (right - i64::from(width)).max(i64::from(work_area.origin.x) + margin) as i32;
        let y = (bottom - i64::from(height)).max(i64::from(work_area.origin.y) + margin) as i32;
        Self {
            monitor_id: monitor.id.clone(),
            work_area,
            x,
            y,
            width,
            height,
            margin_px: Self::DEFAULT_MARGIN_PX,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::monitor::MonitorDescriptor;

    #[allow(clippy::too_many_arguments)]
    fn monitor(
        id: &str,
        x: i32,
        y: i32,
        w: u32,
        h: u32,
        work_x: i32,
        work_y: i32,
        work_w: u32,
        work_h: u32,
    ) -> MonitorDescriptor {
        let bounds = PhysicalBounds::from_xywh(x, y, w, h);
        let work_area = PhysicalBounds::from_xywh(work_x, work_y, work_w, work_h);
        MonitorDescriptor {
            id: id.to_string(),
            label: format!("Monitor {id}"),
            is_primary: true,
            bounds,
            scale_factor: 1.0,
            work_area,
        }
    }

    #[test]
    fn default_metadata_is_empty() {
        let meta = CacheEntryMetadata::default();
        assert_eq!(meta.title, "");
        assert_eq!(meta.note, "");
        assert!(meta.tags.is_empty());
    }

    #[test]
    fn lock_owner_labels_are_stable() {
        assert_eq!(LockOwner::Shelf.label(), "shelf");
        assert_eq!(LockOwner::Editor.label(), "editor");
        assert_eq!(LockOwner::Drag.label(), "drag");
        assert_eq!(LockOwner::Pin.label(), "pin");
    }

    #[test]
    fn shelf_position_sits_24px_inside_work_area() {
        let monitor = monitor(
            "primary", 0, 0, 1920, 1080, 0, 0, 1920, 1040, // taskbar is 40 px tall
        );
        let pos = ShelfPosition::inside_primary_work_area(&monitor);
        // Right edge of the card must be 24 px left of the work-area's
        // right edge.
        let right = i64::from(pos.x) + i64::from(pos.width);
        let wa_right = i64::from(pos.work_area.origin.x) + i64::from(pos.work_area.size.width);
        assert_eq!(wa_right - right, 24);
        // Bottom edge of the card must be 24 px above the work-area's
        // bottom edge.
        let bottom = i64::from(pos.y) + i64::from(pos.height);
        let wa_bottom = i64::from(pos.work_area.origin.y) + i64::from(pos.work_area.size.height);
        assert_eq!(wa_bottom - bottom, 24);
        // The card must not cross the left or top of the work area.
        assert!(pos.x >= pos.work_area.origin.x + 24);
        assert!(pos.y >= pos.work_area.origin.y + 24);
        // The width and height must be the documented defaults.
        assert_eq!(pos.width, ShelfPosition::DEFAULT_WIDTH);
        assert_eq!(pos.height, ShelfPosition::DEFAULT_HEIGHT);
        assert_eq!(pos.margin_px, 24);
    }

    #[test]
    fn shelf_position_handles_negative_origin_work_area() {
        let monitor = monitor("primary", -1920, 0, 1920, 1080, -1920, 0, 1920, 1040);
        let pos = ShelfPosition::inside_primary_work_area(&monitor);
        // Right edge stays 24 px inside the work-area's right edge even
        // with a negative origin.
        let right = i64::from(pos.x) + i64::from(pos.width);
        let wa_right = i64::from(pos.work_area.origin.x) + i64::from(pos.work_area.size.width);
        assert_eq!(wa_right - right, 24);
        // X must land inside the work area.
        assert!(pos.x >= pos.work_area.origin.x);
    }
}
